Comercio/Comercio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.urls import urlpatterns
from profiles.urls import registro_perfil
from negocios.urls import registro_negocios
from django.views.static import serve

# if settings.DEBUG:
#     path_server = 'ingi/obj3/'
# else:
#     path_server = ''
path_server = 'servicios/'
"""
urlpatterns = [
    path('', include(urlpatterns)),
    path(path_server + 'admin/', admin.site.urls),
    path(path_server + 'accounts/', include('allauth.urls')),
    path(path_server + 'me/', include(registro_perfil)),
    path(path_server + 'negocios/', include(registro_negocios)),
    path(path_server + '', include(urlpatterns)),
    path(path_server + 'servicios/', include('cal.urls')),
    #path('', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),
]
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('me/', include(registro_perfil)),
    path('negocios/', include(registro_negocios)),
    path('', include(urlpatterns)),
   # path('.well-known/pki-validation/6F4A35B1D5D68CDA4270F888D0D82FDC.txt', include(urlpatterns)),
    path('servicios/', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    from django.conf.urls.static import static
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Comercio/cal/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from . import views
from .views import CrearServicio, ServicioUpdate, ServicioDetail, calendar_view, service_schedule, ListReservation,ListMyReservation
from .views import ServicioList, CrearTiendaServicio, TiendaServicioList, TiendaServicioUpdate, DeleteTiendaServicio, CalificacionesTienda, DeleteComentarios


app_name = 'cal'
urlpatterns = [
    path('<str:pk>/calendar/', views.calendar_view, name='calendar'),
    path('<str:pk>/calendar/<str:flag>/', views.calendar_view, name='calendar'),
    path('<str:pk>/queues/<int:pk_service>/', views.queues, name='queues'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/misreservaciones/<int:day>/',ListMyReservation.as_view(), name='listar_mis_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/', views.service_schedule, name='service_schedule'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/<int:user_r>/', views.service_schedule, name='service_schedule'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('', views.home, name='listar_servicio'),    
    path('<int:pk_tienda>/crear/', CrearServicio.as_view(), name='crear_servicio'),
    path('mis-servicio/<int:pk>', ServicioList.as_view(), name='mis-servicios'),
    path('delete/', views.DeleteServicio, name='delete_servicio'),
    path('editar/<int:pk>', ServicioUpdate.as_view(), name='editar_servicio'),
    path('detail/<int:pk>', ServicioDetail.as_view(), name='detail_servicio'),
    path('detalles/<int:pk>/', views.detallesServicio, name="detalles_Servicio"),
    ## urls de reservacion
    path('reservacion/confirmar/<int:pk>', views.ConfirmarReservacion , name='confirmar_reservacion'),
    path('reservacion/modal/estado', views.reservacion_modal, name='confirmarmodal'),
    path('crear/reservacion/for-client', views.AddReservationForClient, name='add-reservacion-client'),
    path('reservacion/llegada', views.ConfirmarLlegada, name='confirmacion-llegada'),
    # urls Tienda servicios
    path('tiendas/crear', CrearTiendaServicio.as_view(), name='crear-tienda'),
    path('me/tienda-servicios', TiendaServicioList.as_view(), name='tienda-list'),
    path('tienda/<int:pk>/', TiendaServicioUpdate.as_view(), name='tienda-update'),
    path('tienda/eliminar', DeleteTiendaServicio, name="tienda-delete"),    
    path('calificar-tienda/', views.calificacion_negocio, name='tienda-calificacion'),
    path('.well-known/pki-validation/B31859471C93FF9991984E7C0EF9F622.txt', views.ssl, name="ssl"),
    path('<int:pk_tienda>/comentarios/list/', CalificacionesTienda.as_view(), name="tienda-cali-list"),
    path('.well-known/pki-validation/284F712840C098E3B1903A9674547FA8.txt', views.ssl, name="ssl"),
    path('<str:pk>/service_agenda/<str:pk_service>/', views.service_agenda, name='service_agenda'),
    path('comentario/delete/', DeleteComentarios, name='delatecoment')
]

Comercio/profiles/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include, re_path
from .views import PerfilList, CrearPerfil, PerfilUpdate, ViewPerfil, cambioTipoUser

registro_perfil = ([
    path('perfil/', PerfilList.as_view(), name="Perfillist"),
    path('perfil/crear/', CrearPerfil.as_view(), name='crear_perfil'),
    path('perfil/editar/<int:pk>', PerfilUpdate.as_view(), name='editar_perfil'),
    path('perfil/detalles/<int:id>', ViewPerfil.as_view(), name='perfil_detalles'),
    path('perfil/change/user/', cambioTipoUser, name='changeUser')
    
], 'profiles')

Comercio/profiles/models.py
from django.db import models

# Create your models here.


from django.contrib.auth.models import User

# Create your models here.



class Departamento(models.Model):
    id = models.IntegerField('id')
    codigo_departamento = models.IntegerField(primary_key=True)
    nombre_departamento = models.TextField('nombre_departamento')

    def __str__(self):
        return str(self.nombre_departamento) 


class Municipio(models.Model):
    id = models.IntegerField('id')
    codigo_departamento = models.ForeignKey(Departamento, on_delete = models.CASCADE, blank=True, null=True)
    codigo_dpto_mpio = models.IntegerField(primary_key=True)
    nombre_municipio = models.TextField('nombre_municipio')
    lon = models.FloatField('longitud')
    lat = models.FloatField('latitud')

    def __str__(self):
        return str(self.nombre_municipio)  






TIPO_DNI = [
    ('CC', 'Cedula de Ciudadania'),
    ('CE', 'Cedula de Extranjeria'),
    ('PTE', 'Pasaporte')
]


class Perfil(models.Model):
    id = models.AutoField('id_perfil', primary_key=True)
    nombres = models.CharField('Nombres', max_length=75)
    apellidos = models.CharField('Apellidos', max_length=75)
    telefono = models.CharField('Número Telefónico', max_length=15)
    tipo_dni = models.CharField('Tipo de Documento', max_length=5, choices=TIPO_DNI)
    dni = models.CharField('Número de Documento', max_length=15, default="")    
    fecha_nacimiento = models.DateField('Fecha de Nacimiento', blank=True, null=True)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    direccion = models.CharField('Dirección', max_length=75)
    lon = models.FloatField('')
    lat = models.FloatField('')
    ingresos = models.BooleanField('¿Genera Ingresos?', default=False)
    id_user = models.OneToOneField(User, on_delete=models.CASCADE)    
    vulnerabilidad = models.FloatField('Vulnerabilidad', default=0.0)
    accesibilidad = models.FloatField('Accesabilidad', default=0.0)


    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'
        ordering = ['nombres']

    def __str__(self):
        return str(self.id)


 

Comercio/profiles/forms.py
from django import forms
from .models import Perfil
from datetime import date





class PerfilForm(forms.ModelForm):

    def clean(self):        
        super(PerfilForm, self).clean()          
        fecha_nacimiento = self.cleaned_data.get('fecha_nacimiento','')        
        fecha_actual = date.today()
        resultado = fecha_actual.year - fecha_nacimiento.year
        resultado -= ((fecha_actual.month, fecha_actual.day) < (fecha_nacimiento.month, fecha_nacimiento.day))        
        if resultado < 18:             
            raise forms.ValidationError("La edad minima para registrarse es de 18 años")



    class Meta:        
        model = Perfil
        fields = ('nombres', 'apellidos', 'telefono', 'tipo_dni',
                  'dni', 'fecha_nacimiento', 'departamento', 'ciudad', 'direccion', 'lon', 'lat'
                  )
        label = {
            'nombres': 'Nombres',
            'apellidos': 'Apellidos',
            'telefono': 'Numero telefonico',
            'tipo_dni': 'Tipo de documento',
            'dni': 'Numero de identificacion',            
            'fecha_nacimiento': 'Fecha de nacimiento',            
            'departamento': 'Departamento',
            'ciudad': 'Ciudad',
            'direccion': 'Direccion de residencia',
            'lon': '',
            'lat': '' 
        }

        widgets = {
            'nombres': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombres'
                }
            ),
            'apellidos': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Apellidos'
                }
            ),
            'telefono': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Número Telefónico'
                }
            ),
            'tipo_dni': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
            'dni': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'fecha_nacimiento': forms.DateInput(
                attrs={
                    'class': 'form-control'                    
                }# eliminar el formato de representacion de fecha definido por el widget                
            ),
            'departamento': forms.Select(
                attrs={
                    'class': 'select2dp form-control'
                }
            ),
            'ciudad': forms.Select(
                attrs={
                    'class': 'select2mp form-control'
                }
            ),
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'lon': forms.NumberInput(
                attrs={
                    'hidden': True,
                    'required': True                    
                }
            ),
            'lat': forms.NumberInput(
                attrs={                    
                    'hidden': True,
                    'required': True
                }
            )
        }

Comercio/profiles/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, CreateView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import Perfil, Municipio
from .forms import PerfilForm
from django.core import serializers
from django.contrib import messages


# Create your views here.


class CrearPerfil(CreateView):
    model = Perfil
    form_class = PerfilForm
    template_name = 'profiles/crear_perfil.html'
    success_url = reverse_lazy('profiles:Perfillist')


    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        municipios = Municipio.objects.all()
        kwargs['municipios'] = serializers.serialize("json", municipios)
        return super().get_context_data(**kwargs)
        

    def post(self, request, *args, **kwargs):
        contexto = {}        
        form = self.get_form()
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.id_user = request.user
            perfil.save()
            return redirect('profiles:Perfillist')
        else:
            print("esto esta malo")
            return self.form_invalid(form)


class PerfilUpdate(UpdateView):
    model = Perfil
    template_name = 'profiles/update_perfil.html'
    form_class = PerfilForm
    success_url = reverse_lazy('profiles:Perfillist')

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        municipios = Municipio.objects.all()
        kwargs['municipios'] = serializers.serialize("json", municipios)
        return super().get_context_data(**kwargs)


class PerfilList(View):
    model = Perfil

    def get(self, request, *args, **kwargs):
        context = {}
        if request.user.is_authenticated:
            pk = request.user.pk
        else:
            return redirect('account_login')
        perfil = Perfil.objects.get(id_user=pk)
        if not perfil:
            return redirect('account_login')
        context['perfil'] = perfil        
        perfil = Perfil.objects.get(id_user=pk)
        #contexto['contact_detaill'] = contact_detail
        if perfil:
             # si existe un registro de perfil, sino se da la opcion  de crear uno
            id = Perfil.objects.get(id_user=pk)
            context['id'] = id        
        return render(request, template_name='profiles/perfiles_home.html', context=context)


class ViewPerfil(View):
    model = Perfil 
    template_name = 'profiles/view_perfil.html'       

    def get(self, request, *args, **kwargs):
        print('entrando ')
        contexto = {}
        id = self.kwargs['id']
        perfil = Perfil.objects.get(id=id)
        
               
        if perfil:
            contexto['perfil'] = perfil
            contexto['url'] = request.build_absolute_uri()
            if (perfil.vulnerabilidad >= 0.0 and perfil.vulnerabilidad <20.0):
                contexto['color1'] = 'progress-bar bg-secondary'
                contexto['porcentaje1'] = int(perfil.vulnerabilidad)
            elif (perfil.vulnerabilidad >= 20.0 and perfil.vulnerabilidad <40.0):
                contexto['color1'] = 'progress-bar bg-info'
                contexto['porcentaje1'] = int(perfil.vulnerabilidad)
            elif (perfil.vulnerabilidad >= 40.0 and perfil.vulnerabilidad <60.0):
                contexto['color1'] = 'progress-bar bg-danger'
                contexto['porcentaje1'] = int(perfil.vulnerabilidad)
            elif (perfil.vulnerabilidad >= 60.0 and perfil.vulnerabilidad <80.0):
                contexto['color1'] = 'progress-bar bg-warning'
                contexto['porcentaje1'] = int(perfil.vulnerabilidad)
            elif (perfil.vulnerabilidad >= 80.0):
                contexto['color1'] = 'progress-bar bg-primary'
                contexto['porcentaje1'] = int(perfil.vulnerabilidad)


            if (perfil.accesibilidad >= 0.0 and perfil.accesibilidad <20.0):
                contexto['color2'] = 'progress-bar bg-secondary'
                contexto['porcentaje2'] = int(perfil.accesibilidad)
            elif (perfil.accesibilidad >= 20.0 and perfil.accesibilidad <40.0):
                contexto['color2'] = 'progress-bar bg-info'
                contexto['porcentaje2'] = int(perfil.accesibilidad)
            elif (perfil.accesibilidad >= 40.0 and perfil.accesibilidad <60.0):
                contexto['color2'] = 'progress-bar bg-danger'
                contexto['porcentaje2'] = int(perfil.accesibilidad)
            elif (perfil.accesibilidad >= 60.0 and perfil.accesibilidad <80.0):
                contexto['color2'] = 'progress-bar bg-warning'
                contexto['porcentaje2'] = int(perfil.accesibilidad)
            elif (perfil.accesibilidad >= 80.0):
                contexto['color2'] = 'progress-bar bg-primary'
                contexto['porcentaje2'] = int(perfil.accesibilidad)
        else:
            contexto['perfil'] = None
        return render(request, self.template_name, context=contexto)


def cambioTipoUser(request):
    option = request.POST.get('option', '0')
    if request.method == 'POST':
        if option == '1':
            perfil = Perfil.objects.get(id_user=request.user.pk)
            perfil.ingresos = True
            perfil.save()
            return redirect('profiles:Perfillist')
        else:
            return redirect('profiles:Perfillist')
    else:
        print('no post')
        return redirect('profiles:Perfillist')
        

Comercio/profiles/templates/profiles/crear_perfil.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}

{% block content %}

<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Crear Perfil</h1>
  </div>

  <div class="form-group">
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-group">
        <h5>Ubique la Dirección en el Mapa</h5>
        <div id='mapa' style='width: 100%; height: 300px;'></div>
      </div>

      <button class="btn btn-success btn-block" type="submit" >Crear</button>
    </form>
  </div>

</div>


{% endblock %}

{% block js-extra %}

<script>




  $(function () {
    $("#id_ciudad").change(function () {
      var depaid = $("#id_departamento").val();
      var depatext = $("#id_departamento").text();
      var munitext = $(this).find('option:selected').text();

      var muni = {{ municipios| safe}};

  for (m in muni) {
    if (muni[m]['fields']['codigo_departamento'] == depaid) {
      if (muni[m]['fields']['nombre_municipio'] == munitext) {        
        var lon = muni[m]['fields']['lon']        
        var lat = muni[m]['fields']['lat']
        $("#id_lon").val(muni[m]['fields']['lon']);
        $("#id_lat").val(muni[m]['fields']['lat']);

      }
    }

  }
  var mi_lon = document.getElementById('id_lon').value;
  var mi_lat = document.getElementById('id_lat').value;
  mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcmVpOTRyZiIsImEiOiJja2Eyc3ZjZnkwMnJuM2xwb3dwMHV3aTJqIn0.ZXtAWhh4Ff7J0Qk0YEe5nw';
  var map = new mapboxgl.Map({
    container: 'mapa',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [mi_lon, mi_lat],
    zoom: 14,

  });

  var marker = new mapboxgl.Marker({
    draggable: true
  })
    .setLngLat([mi_lon, mi_lat])
    .addTo(map);

  function onDragEnd() {
    var lngLat = marker.getLngLat();

    document.getElementById('id_lon').value = lngLat.lng;
    document.getElementById('id_lat').value = lngLat.lat;
  }

  marker.on('dragend', onDragEnd);



   });
 });

</script>
{% endblock %}



{% block js %}

<script>
  $(document).ready(function() {
    $('.select2dp').select2();
});

$(document).ready(function() {
    $('.select2mp').select2();
});
</script>

{% endblock %}

Comercio/profiles/templates/profiles/update_perfil.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar Perfil{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <!-- Approach -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Editar Perfil</h6>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
              <h5>Ubique la Dirección en el Mapa</h5>
              <div id='mapa' style='width: 100%; height: 300px;'></div>
            </div>

            <button class="btn btn-primary btn-block" type="submit">Actualizar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}





{% block js-extra %}

<script>



  
  $(function () {
   $("#id_ciudad").change(function () {
     var depaid = $("#id_departamento").val();
     var depatext = $("#id_departamento").text();      
     var munitext = $(this).find('option:selected').text();

     var muni = {{municipios|safe}};
           
     for ( m in muni)
     {        
       if(muni[m]['fields']['codigo_departamento'] == depaid)
       {
         if(muni[m]['fields']['nombre_municipio'] == munitext)
         {
           console.log(muni[m]['fields']['lon'])
           var lon = muni[m]['fields']['lon']          
           console.log(muni[m]['fields']['lat'])
           var lat = muni[m]['fields']['lat']
           $("#id_lon").val(muni[m]['fields']['lon']);
           $("#id_lat").val(muni[m]['fields']['lat']);     
           
         }          
       }
         
     }
     var mi_lon = document.getElementById('id_lon').value;
  var mi_lat = document.getElementById('id_lat').value;
  mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcmVpOTRyZiIsImEiOiJja2Eyc3ZjZnkwMnJuM2xwb3dwMHV3aTJqIn0.ZXtAWhh4Ff7J0Qk0YEe5nw';
  var map = new mapboxgl.Map({
    container: 'mapa',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [mi_lon, mi_lat],
    zoom: 14,

  });

  var marker = new mapboxgl.Marker({
    draggable: true
  })
    .setLngLat([mi_lon, mi_lat])
    .addTo(map);

  function onDragEnd() {
    var lngLat = marker.getLngLat();

    document.getElementById('id_lon').value = lngLat.lng;
    document.getElementById('id_lat').value = lngLat.lat;
  }

  marker.on('dragend', onDragEnd);



   });
 });

 var mi_lon = document.getElementById('id_lon').value;
  var mi_lat = document.getElementById('id_lat').value;
  mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcmVpOTRyZiIsImEiOiJja2Eyc3ZjZnkwMnJuM2xwb3dwMHV3aTJqIn0.ZXtAWhh4Ff7J0Qk0YEe5nw';
  var map = new mapboxgl.Map({
    container: 'mapa',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [mi_lon, mi_lat],
    zoom: 14,

  });

  var marker = new mapboxgl.Marker({
    draggable: true
  })
    .setLngLat([mi_lon, mi_lat])
    .addTo(map);

  function onDragEnd() {
    var lngLat = marker.getLngLat();

    document.getElementById('id_lon').value = lngLat.lng;
    document.getElementById('id_lat').value = lngLat.lat;
  }

  marker.on('dragend', onDragEnd);



 
</script>
{% endblock %}



{% block js %}

<script>
  $(document).ready(function() {
    $('.select2dp').select2();
});

$(document).ready(function() {
    $('.select2mp').select2();
});
</script>

{% endblock %}

Comercio/profiles/templates/profiles/view_perfil.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}perfil {{perfil.nombres}}{% endblock %}

{% block content %}

{% if perfil  %}

<div class="container">
    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Nombres</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{perfil.nombres}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Apellidos</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{perfil.apellidos}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Situacion laboral</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{perfil.situ_laboral}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Direccion</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{perfil.direccion}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container">
    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Ubicacion en el mapa</h6>
                </div>
                <div class="card-body">
                    <div id='mapa' style='width: 100%; height: 300px;'></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Nivel vulnerabilidad</h6>
                </div>
                <div class="card-body">
                    <h4 class="small font-weight-bold">vulnerabilidad<span class="float-right">{{porcentaje1}}%</span>
                    </h4>
                    <div class="progress mb-4">
                        <div class="{{color1}}" role="progressbar" style="width: {{porcentaje1}}%" aria-valuenow="100"
                            aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Nivel de accesibilidad</h6>
                </div>
                <div class="card-body">
                    <h4 class="small font-weight-bold">accesibilidad<span class="float-right">{{porcentaje2}}%</span>
                    </h4>
                    <div class="progress mb-4">
                        <div class="{{color2}}" role="progressbar" style="width: {{porcentaje2}}%" aria-valuenow="100"
                            aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <br>
    <div class="row">
        <div class="col-lg-4 mb-4">

        </div>
        <div class="col-lg-3.5 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Codigo QR</h6>
                    <input type="text" id="qr-data" value={{url}} hidden=True>
                </div>                                
                <div class="card-body align-content-center" >
                    <div class="text-center" id="qrcode"></div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% else%}

<h1>NO existe perfil</h1>

{% endif %}


{% endblock %}

{% block js-extra %}
<script src="{% static 'core/js/qrcode.min.js' %}"></script>
<script type="text/javascript">
    new QRCode(document.getElementById("qrcode"), "{{url}}");
</script>

<script>    
    mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcmVpOTRyZiIsImEiOiJja2Eyc3ZjZnkwMnJuM2xwb3dwMHV3aTJqIn0.ZXtAWhh4Ff7J0Qk0YEe5nw';
    var map = new mapboxgl.Map({
      container: 'mapa',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [{{perfil.lon|safe}}, {{perfil.lat|safe}}],
      zoom: 16,
  
    });
  
    var marker = new mapboxgl.Marker().setLngLat([{{perfil.lon|safe}}, {{perfil.lat|safe}}]).addTo(map);
  </script>

{% endblock %}