Comercio/Comercio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.urls import urlpatterns
from profiles.urls import registro_perfil
from negocios.urls import registro_negocios
from django.views.static import serve

# if settings.DEBUG:
#     path_server = 'ingi/obj3/'
# else:
#     path_server = ''
path_server = 'servicios/'
"""
urlpatterns = [
    path('', include(urlpatterns)),
    path(path_server + 'admin/', admin.site.urls),
    path(path_server + 'accounts/', include('allauth.urls')),
    path(path_server + 'me/', include(registro_perfil)),
    path(path_server + 'negocios/', include(registro_negocios)),
    path(path_server + '', include(urlpatterns)),
    path(path_server + 'servicios/', include('cal.urls')),
    #path('', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),
]
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('me/', include(registro_perfil)),
    path('negocios/', include(registro_negocios)),
    path('', include(urlpatterns)),
   # path('.well-known/pki-validation/6F4A35B1D5D68CDA4270F888D0D82FDC.txt', include(urlpatterns)),
    path('servicios/', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    from django.conf.urls.static import static
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Comercio/cal/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from . import views
from .views import CrearServicio, ServicioUpdate, ServicioDetail, calendar_view, service_schedule, ListReservation,ListMyReservation
from .views import ServicioList, CrearTiendaServicio, TiendaServicioList, TiendaServicioUpdate, DeleteTiendaServicio, CalificacionesTienda, DeleteComentarios


app_name = 'cal'
urlpatterns = [
    path('<str:pk>/calendar/', views.calendar_view, name='calendar'),
    path('<str:pk>/calendar/<str:flag>/', views.calendar_view, name='calendar'),
    path('<str:pk>/queues/<int:pk_service>/', views.queues, name='queues'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/misreservaciones/<int:day>/',ListMyReservation.as_view(), name='listar_mis_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/', views.service_schedule, name='service_schedule'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/<int:user_r>/', views.service_schedule, name='service_schedule'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('', views.home, name='listar_servicio'),    
    path('<int:pk_tienda>/crear/', CrearServicio.as_view(), name='crear_servicio'),
    path('mis-servicio/<int:pk>', ServicioList.as_view(), name='mis-servicios'),
    path('delete/', views.DeleteServicio, name='delete_servicio'),
    path('editar/<int:pk>', ServicioUpdate.as_view(), name='editar_servicio'),
    path('detail/<int:pk>', ServicioDetail.as_view(), name='detail_servicio'),
    path('detalles/<int:pk>/', views.detallesServicio, name="detalles_Servicio"),
    ## urls de reservacion
    path('reservacion/confirmar/<int:pk>', views.ConfirmarReservacion , name='confirmar_reservacion'),
    path('reservacion/modal/estado', views.reservacion_modal, name='confirmarmodal'),
    path('crear/reservacion/for-client', views.AddReservationForClient, name='add-reservacion-client'),
    path('reservacion/llegada', views.ConfirmarLlegada, name='confirmacion-llegada'),
    # urls Tienda servicios
    path('tiendas/crear', CrearTiendaServicio.as_view(), name='crear-tienda'),
    path('me/tienda-servicios', TiendaServicioList.as_view(), name='tienda-list'),
    path('tienda/<int:pk>/', TiendaServicioUpdate.as_view(), name='tienda-update'),
    path('tienda/eliminar', DeleteTiendaServicio, name="tienda-delete"),    
    path('calificar-tienda/', views.calificacion_negocio, name='tienda-calificacion'),
    path('.well-known/pki-validation/B31859471C93FF9991984E7C0EF9F622.txt', views.ssl, name="ssl"),
    path('<int:pk_tienda>/comentarios/list/', CalificacionesTienda.as_view(), name="tienda-cali-list"),
    path('.well-known/pki-validation/284F712840C098E3B1903A9674547FA8.txt', views.ssl, name="ssl"),
    path('<str:pk>/service_agenda/<str:pk_service>/', views.service_agenda, name='service_agenda'),
    path('comentario/delete/', DeleteComentarios, name='delatecoment')
]

Comercio/cal/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from profiles.models import Perfil


grado_teletrabajo = [
    ('LOCAL', 'Mi local'),
    ('DOMICILIO', 'Domicilio'),
    ('DEFINIR', 'A Definir')
]



class TiendaServicio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField('Nombre del Establecimiento', max_length=50)
    fachada = models.ImageField(
        'Fachada del Establecimiento', upload_to='fachadas/%Y/%m/%d/')
    direccion = models.CharField('Dirección', max_length=50)
    telefono = models.CharField('Número Telefónico', max_length=10)
    email_negocio = models.EmailField('Correo Electrónico del Negocio', blank=True)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, verbose_name='Usuario asociado')
    lon = models.FloatField('')
    lat = models.FloatField('')
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True , verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = 'Tienda de servicios'
        ordering = ['-updated']
        verbose_name_plural = 'Tiendas de servicios'
        unique_together = (('nombre', 'direccion'),)


    def __str__(self):
        return self.nombre
    


class CategoriaServicio(models.Model):
    nombre = models.CharField('Nombre del servicio', max_length=75)

    class Meta:
        verbose_name = 'Categoría del servicio'
        verbose_name_plural = 'Categoría de los servicios'

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    id = models.AutoField(primary_key=True)
    tienda = models.ForeignKey(TiendaServicio, on_delete=models.CASCADE)
    nombre = models.CharField('Servicio', max_length=100)    
    foto_servicio = models.ImageField('Foto del Establecimiento', upload_to='servicios/locales/%Y/%m/%d/')    
    modalidad = models.CharField('Modalidad de Trabajo', max_length=50,
                                 choices=grado_teletrabajo, default=grado_teletrabajo[0])  
    precio = models.IntegerField('precio', default=0, null=True)    
    descripcion = models.TextField('Descripción', null=True) 
    categoria = models.ForeignKey(CategoriaServicio, on_delete=models.CASCADE)
    time = models.IntegerField('Tiempo de Servicio')
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True , verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Fecha de edición")
      
    class Meta:
        verbose_name = 'Servicio'
        ordering = ['-updated']
        verbose_name_plural = 'Servicios'

    def __str__(self):
        return self.nombre

class ScheduleServicio(models.Model):
    day = models.CharField(max_length=15)
    active = models.BooleanField(default=True)
    from_1 = models.CharField(max_length=5)# hora inicial
    to_1 = models.CharField(max_length=5)
    from_2 = models.CharField(max_length=5)
    to_2 = models.CharField(max_length=5)# hora final
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
     

    def __str__(self):
        return self.day
    

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField('', blank=True, null=True)
    estado = models.BooleanField('Estado', default=False)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def get_html_url(self):
        """Esta funcion retorna la url del modelo
        y la @property sirve para poderacceder a la funcion como un parametro
        normal"""
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

    def __str__(self):
        return self.title

class Reservation(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField()
    from_t = models.TimeField()
    to_t = models.TimeField()
    estado = models.BooleanField('estado',default=False)
    confirmacion_llegada = models.BooleanField('Confirmacion llegada', default=False)
    pendiente = models.BooleanField('pendiente', default=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True , verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = 'Reservaciones'
        verbose_name_plural = 'Reservaciones'
        ordering = ['-updated']

    def __str__(self):
        return self.servicio.nombre
    
class Queue(models.Model):
    name = models.CharField(max_length=200)
    people_per_time = models.IntegerField()
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)

    def __str__(self):
        return self.name




class CalificacionTiendaServicio(models.Model):
    id = models.AutoField('id', primary_key=True)
    comentario = models.TextField('Comentario', blank=True)
    puntuacion = models.IntegerField('Puntuacion')    
    tienda = models.ForeignKey(TiendaServicio, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")


    class Meta:
        verbose_name = 'Calificacion'
        ordering = ['-created', 'puntuacion']
        verbose_name_plural = 'Calificaciones'

    def __str__(self):
        return str(self.puntuacion)

Comercio/cal/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from cal.models import Event, Servicio, ScheduleServicio, TiendaServicio


class TiendaServicioForm(forms.ModelForm):
  class Meta:
    model = TiendaServicio
    fields = ('nombre', 'fachada', 'direccion',
              'telefono', 'email_negocio', 'lon', 'lat')
    label = {
        'nombre': 'Servicio',
        'fachada': 'Foto del Establecimiento',        
        'direccion': 'Dirección',        
        'telefono': 'Telefono del Establecimiento',        
        'email_negocio': 'Email del Establecimiento',
        'lon': '',
        'lat': '',     
    }

    widgets = {
        'nombre': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Nombre del Servicio'
            }
        ),
        'fachada': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file mt-3'
                }
        ),
        'direccion': forms.TextInput(
            attrs={
                'class': 'form-control',                
            }
        ),                        
        'telefono': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Donde te van a contactar'
            }
        ),                       
        'email_negocio': forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Correo Electrónico del Establecimiento'
            }
        ),
        'lon': forms.NumberInput(
                attrs={
                    'hidden': True,
                    'required': True
                }
            ),
        'lat': forms.NumberInput(
                attrs={
                    'hidden': True,
                    'required': True
                }
        )
    }








class ScheduleServicioForm(forms.ModelForm):
    class Meta:
        model = ScheduleServicio
        fields = (
            'day',
            'active',
            'from_1',
            'to_1',
            'from_2',
            'to_2',
        )


class ServicioForm(forms.ModelForm):
  class Meta:
    model = Servicio
    fields = ('nombre', 'modalidad', 'foto_servicio', 'precio', 'descripcion',
              'categoria', 'time')
    label = {
        'nombre': 'Servicio',
        'modalidad': 'Modalidad del servicio',   
        'precio': 'Precio del Artículo', 
        'descripcion': 'Descripción',
        'foto_servicio': 'Foto del Establecimiento o servicio',        
        'categoria': 'Categoría del servicio',        
        'time': 'Franja de tiempo',        
    }

    widgets = {
        'nombre': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Nombre del servicio'
            }
        ),
        'foto_servicio': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file mt-3'
                }
        ),
        'modalidad': forms.Select(
            attrs={
                'class': 'form-control'
            }
        ), 
        'precio': forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Precio del servicio'
            }
        ),   
        'descripcion': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Descripción'
            }
        ),                        
        'categoria': forms.Select(
            attrs={
                'class': 'form-control'
            }
        ),                       
        'time': forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Tiempo en Minutos'
            }
        )
    }


class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields    
    widgets = {
        'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        'end_time': DateInput(attrs={'type': 'datetime-local', 'hidden': True}, format='%Y-%m-%dT%H:%M'),
    }
    fields = (
        'title', 'description', 'start_time', 'end_time'
    )

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)


estado = [
    ('True', 'Aceptar'),
    ('False', 'No aceptar')
    
]

class EventConfirmationForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = (
            'estado',
        )
        widgets = {
            'estado': forms.Select(
                attrs={
                    'class': 'form-control'
                },
                choices=estado
            )        
        }

Comercio/cal/templates/cal/correo_usuario.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de reserva</title>
</head>
<body>
    <h2>Su solicitud de agendamiento ha sido aprobada para el servicio <strong>{{servicio}}</strong></h2>
    <h2>Datos de contacto: </h2>
    <p>Telefono: {{telefono}}</p>
    <p>Fecha: {{day}}</p>
    <p>Horario: {{inicio}} - {{fin}}</p>
</body>
</html>

Comercio/cal/templates/cal/correo_usuario_cancelar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de reserva</title>
</head>
<body>
    <h2>Su solicitud de agendamiento ha sido RECHAZADA para el servicio <strong>{{servicio}}</strong></h2>
    <h2>Pasos a seguir!</h2>
    <a href="{{mensaje}}">Enviale un mensaje</a>
    <h2>Recuerda que puedes hacer mas reservas</h2>
    <a href="https://{{host}}{% url 'core:home' %}">reserva Aquí!!</a>
</body>
</html>

Comercio/cal/templates/cal/event.html
{% extends 'cal/base.html' %}


{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Reservar </button></td></tr>
  </table>
</form>

{% endblock %}

Comercio/cal/templates/cal/list_servicio.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Listado negocios{% endblock %}
{% block control %}
{% include 'profiles/controlnav.html' %}
{% endblock %}
{% block content %}
<main role="main">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <a href="{% url 'cal:crear_servicio' pk_tienda=id %}" class="btn btn-success btn-block">Crear Servicio</a>            
        </div>
        <div class="row">

            {% if servicios %}

            {% for servicio in servicios %}
            <div class="col-lg-4 mb-4">
                <div class="card shadow mb-4 text-center">
                    <div class="card-header bg-info text-white">
                        Servicio: {{servicio.nombre}}
                    </div>
                    <div class="card-body">
                      <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" src="{{servicio.foto_servicio.url}}" alt="{{servicio.nombre}}"
                          style="width: 25rem;">
                      </div>
                        <h5 class="card-title"></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><strong>{{servicio.direccion}}</strong></h6>
                        <p class="card-text">{{servicio.modalidad}}</p>
                        <p class="card-text">{{servicio.telefono}}</p>
                        <a href="{% url 'cal:calendar' pk=servicio.tienda.perfil.id_user.pk flag='1' %}" class="btn btn-info btn-block mb-2">Ver
                          agenda</a> 
                        <a href="{% url 'cal:queues' pk=user.id pk_service=servicio.id %}" class="btn btn-success btn-block"><i
                            class="fas fa-fw fa-tachometer-alt"></i>Crear cola</a>      
                        <a href="{% url 'cal:service_agenda' pk=user.id pk_service=servicio.id %}" class="btn btn-success btn-block"><i
                              class="fas fa-fw fa-tachometer-alt"></i>Gestionar Horario</a>                   
                        <a href="{% url 'cal:editar_servicio' servicio.id %}" class="btn btn-success btn-block mb-2">Actualizar
                            servicio</a>
                            <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#deleteModal" data-whatever="{{servicio.id}}">Eliminar</button>
                    </div>
                </div><br>
            </div>
            {% endfor %}
            {% else %}

            <h1>No tienes servicios registrados!</h1>

            {% endif %}
        </div>

    </div>





    <!-- Menú de paginación -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
            {% endif %}
            {% for i in paginator.page_range %}
            <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item ">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}    
</main>


    <!-- Ventana modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Eliminar Servicio</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="GET" action="{% url 'cal:delete_servicio' %}">          
              <div class="form-group">            
                <input type="text" class="form-control" id="recipient-name" name="pk" hidden>
              </div>  
              <button type="submit" class="btn btn-primary btn-block">Eliminar</button>
              <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">Cancelar</button>                
            </form>
          </div>                  
        </div>
      </div>
    </div>
    

{% endblock %}


{% block js-extra %}

<script>

$('#deleteModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) 
  var recipient = button.data('whatever') 
  var modal = $(this)  
  modal.find('.modal-body input').val(recipient)
})

</script>


{% endblock %}

Comercio/cal/templates/cal/list_tienda.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Listado tiendas de servicios{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            
      <a href="{% url 'cal:crear-tienda' %}" class="btn btn-success btn-block mb-2">Registra tus Servicios</a>
  </div>
    <div class="row">

      {% if tiendas %}


      {% for tienda in tiendas %}
      <div class="col-lg-4 mb-4">
        <div class="card shadow mb-4 text-center">
          <div class="card-header bg-info text-white">
            Negocio: {{tienda.nombre}}
          </div>
          <div class="card-body">
            <div class="text-center">
              {% if tienda.fachada %}
              <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                src="{{ tienda.fachada.url }}" alt="">
              {% else %}
              <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
              src="{% static 'core/img/sigelo.png' %}" alt="">
              {% endif %}
            </div>
            <h5 class="card-title"></h5>
            <h6 class="card-subtitle mb-2 text-muted">Registrado desde - {{tienda.created}}</h6>            
            <a href="{% url 'cal:crear_servicio' pk_tienda=tienda.id %}" class="btn btn-success btn-block mb-2">Crear servicio</a>
            <a href="{% url 'cal:mis-servicios' pk=tienda.id %}" class="btn btn-primary btn-block mb-2">Ver
              servicios</a>
            <!-- <a href="{% url 'cal:listar_servicio' %}" class="btn btn-success btn-block"><i
                class=""></i>Gestión de Horarios</a>                  -->
            <a href="{% url 'cal:tienda-update' pk=tienda.id %}" class="btn btn-warning btn-block mb-2">Editar</a>
            <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#deleteModal" data-whatever="{{tienda.pk}}">Eliminar</button>
          </div>
        </div><br>
      </div>
      {% endfor %}
      {% else %}      
      <h1>No tienes servicios registrados!</h1>

      {% endif %}
    </div>
  </div>

  </div>


  <!-- Menú de paginación -->
  {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
      </li>
      {% endif %}
      {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
  </div>
</main>

<!-- Ventana modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Eliminar Negocio</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="GET" action="{% url 'cal:tienda-delete' %}">          
          <div class="form-group">            
            <input type="text" class="form-control" id="recipient-name" name="pk" hidden>
          </div>  
          <button type="submit" class="btn btn-primary btn-block">Eliminar</button>
          <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">Cancelar</button>                
        </form>
      </div>                  
    </div>
  </div>
</div>






{% endblock %}


{% block js-extra %}

<script>

$('#deleteModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) 
  var recipient = button.data('whatever') 
  var modal = $(this)  
  modal.find('.modal-body input').val(recipient)
})

</script>

{% endblock %}