Comercio/Comercio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.urls import urlpatterns
from profiles.urls import registro_perfil
from negocios.urls import registro_negocios
from django.views.static import serve

# if settings.DEBUG:
#     path_server = 'ingi/obj3/'
# else:
#     path_server = ''
path_server = 'servicios/'
"""
urlpatterns = [
    path('', include(urlpatterns)),
    path(path_server + 'admin/', admin.site.urls),
    path(path_server + 'accounts/', include('allauth.urls')),
    path(path_server + 'me/', include(registro_perfil)),
    path(path_server + 'negocios/', include(registro_negocios)),
    path(path_server + '', include(urlpatterns)),
    path(path_server + 'servicios/', include('cal.urls')),
    #path('', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),
]
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('me/', include(registro_perfil)),
    path('negocios/', include(registro_negocios)),
    path('', include(urlpatterns)),
   # path('.well-known/pki-validation/6F4A35B1D5D68CDA4270F888D0D82FDC.txt', include(urlpatterns)),
    path('servicios/', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    from django.conf.urls.static import static
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Comercio/cal/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from . import views
from .views import CrearServicio, ServicioUpdate, ServicioDetail, calendar_view, service_schedule, ListReservation,ListMyReservation
from .views import ServicioList, CrearTiendaServicio, TiendaServicioList, TiendaServicioUpdate, DeleteTiendaServicio, CalificacionesTienda, DeleteComentarios


app_name = 'cal'
urlpatterns = [
    path('<str:pk>/calendar/', views.calendar_view, name='calendar'),
    path('<str:pk>/calendar/<str:flag>/', views.calendar_view, name='calendar'),
    path('<str:pk>/queues/<int:pk_service>/', views.queues, name='queues'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/misreservaciones/<int:day>/',ListMyReservation.as_view(), name='listar_mis_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/', views.service_schedule, name='service_schedule'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/<int:user_r>/', views.service_schedule, name='service_schedule'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('', views.home, name='listar_servicio'),    
    path('<int:pk_tienda>/crear/', CrearServicio.as_view(), name='crear_servicio'),
    path('mis-servicio/<int:pk>', ServicioList.as_view(), name='mis-servicios'),
    path('delete/', views.DeleteServicio, name='delete_servicio'),
    path('editar/<int:pk>', ServicioUpdate.as_view(), name='editar_servicio'),
    path('detail/<int:pk>', ServicioDetail.as_view(), name='detail_servicio'),
    path('detalles/<int:pk>/', views.detallesServicio, name="detalles_Servicio"),
    ## urls de reservacion
    path('reservacion/confirmar/<int:pk>', views.ConfirmarReservacion , name='confirmar_reservacion'),
    path('reservacion/modal/estado', views.reservacion_modal, name='confirmarmodal'),
    path('crear/reservacion/for-client', views.AddReservationForClient, name='add-reservacion-client'),
    path('reservacion/llegada', views.ConfirmarLlegada, name='confirmacion-llegada'),
    # urls Tienda servicios
    path('tiendas/crear', CrearTiendaServicio.as_view(), name='crear-tienda'),
    path('me/tienda-servicios', TiendaServicioList.as_view(), name='tienda-list'),
    path('tienda/<int:pk>/', TiendaServicioUpdate.as_view(), name='tienda-update'),
    path('tienda/eliminar', DeleteTiendaServicio, name="tienda-delete"),    
    path('calificar-tienda/', views.calificacion_negocio, name='tienda-calificacion'),
    path('.well-known/pki-validation/B31859471C93FF9991984E7C0EF9F622.txt', views.ssl, name="ssl"),
    path('<int:pk_tienda>/comentarios/list/', CalificacionesTienda.as_view(), name="tienda-cali-list"),
    path('.well-known/pki-validation/284F712840C098E3B1903A9674547FA8.txt', views.ssl, name="ssl"),
    path('<str:pk>/service_agenda/<str:pk_service>/', views.service_agenda, name='service_agenda'),
    path('comentario/delete/', DeleteComentarios, name='delatecoment')
]

Comercio/negocios/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import CrearNegocio, NegocioUpdate, NegocioListView, NegocioDetail, DeleteNegocio
from .views import CrearProducto, ProductoUpdate, ListProductos, CalificacionesNegocio, DeleteComentarios
from . import views


registro_negocios = ([
    path('', NegocioListView.as_view(), name='list_negocios'),
    path('<int:pk_negocio>/detail/', views.detailNegocioProducto, name='detail_negocio'),
    path('delete/', views.DeleteNegocio, name='delete_negocios'),
    path('<int:pk>/cart/', views.cart, name="cart"),
    path('<int:pk>/checkout/', views.checkout, name="checkout"),
    path('<int:pk>/update_item', views.updateItem, name="update_item"),
    path('<int:pk>/store_detail/', views.store_detail, name='store_detail'),
    path('<int:pk>/process_order', views.processOrder, name="process_order"),
    path('<int:pk_order>/<int:opc>/confirmar_orden', views.ConfirmarOrden, name="confirmar_orden"),
    path('<int:pk>/ordenes/', views.Ordenes, name='ordenes'),
    path('<int:pk_order>/<int:pk>/ver_orden/', views.VerOrden, name='ver_orden'),
    path('<int:pk_order>/<int:pk>/', views.EnvioPedido, name='envio_pedido'),
    path('<int:pk>/pedidos/', views.Pedidos, name='pedidos'),
    path('stor/', views.store, name="stor"),
    path('crear/', CrearNegocio.as_view(), name='crear_negocio'),
    path('editar/<int:pk>', NegocioUpdate.as_view(), name='editar_negocio'),
    path('producto/crear/<int:pk_negocio>/', CrearProducto.as_view(), name='crear_producto'),
    path('producto/editar/<int:pk>', ProductoUpdate.as_view(), name='editar_producto'),
    path('search/', views.search, name="search"),
    path('producto/<int:id>/list', ListProductos.as_view(), name='list_producto'),
    path('producto/delete', views.DeleteProducto, name='delete_producto'),
    path('calificacion-negocio/', views.calificacion_negocio, name='calificacion_negocio'),
    path('<int:pk>/comentarios/list/', CalificacionesNegocio.as_view(), name="cali_list"),
    path('comentario/delete/', DeleteComentarios, name='delatecoment')
], 'negocios')

Comercio/negocios/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Perfil

# Create your models here.


class CategoriaNegocios(models.Model):
    nombre = models.CharField('Nombre', max_length=55)

    class Meta:
        verbose_name = 'Categoria de negocio'
        ordering = ['-nombre']
        verbose_name_plural = 'Categorias de negocios'

    def __str__(self):
        return self.nombre


class Negocio(models.Model):
    id = models.AutoField('id', primary_key=True)
    nombre = models.CharField('Nombre del Establecimiento', max_length=70)
    fachada = models.ImageField(
        'Fachada del Establecimiento', upload_to='fachadas/%Y/%m/%d/')
    direccion = models.CharField('Dirección', max_length=50)
    telefono = models.CharField('Número Telefónico', max_length=10)
    domicilio = models.BooleanField('Servicio de Domicilio')
    costo = models.CharField('', max_length=10, default='0')
    email_negocio = models.EmailField('Correo Electrónico del Negocio', blank=True)
    categoria = models.ForeignKey(CategoriaNegocios, on_delete=models.CASCADE, verbose_name='Categoría')
    descripcion = models.TextField('Descripción')
    lon = models.FloatField('')
    lat = models.FloatField('')
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, verbose_name='Usuario asociado')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")


    class Meta:
        verbose_name = 'Negocio'
        ordering = ['-created']
        verbose_name_plural ='Negocios'
        unique_together = (('nombre', 'direccion'),)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    id = models.AutoField('id', primary_key=True)
    nombre = models.CharField('nombre', max_length=55)
    foto = models.ImageField('Imagen del producto', upload_to='productos/%Y/%m/%d/')
    precio = models.IntegerField('precio') 
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = 'Producto'
        ordering = ['-updated', 'nombre']
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.nombre




class CalificacionNegocio(models.Model):
    id = models.AutoField('id', primary_key=True)
    comentario = models.TextField('Comentario', blank=True)
    puntuacion = models.IntegerField('Puntuacion')    
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")


    class Meta:
        verbose_name = 'Calificacion'
        ordering = ['-created', 'puntuacion']
        verbose_name_plural = 'Calificaciones'

    def __str__(self):
        return str(self.puntuacion)


""" class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200)

	def __str__(self):
		return self.name """


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=200, null=False)
    confirma_cliente = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    def __str__(self):
        return str(self.id)
        
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        if len(orderitems) >= 1:
            total = sum([item.get_total for item in orderitems])+self.get_cart_domicilio
        else:
            total = 0
        return total 

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total 


    @property
    def get_cart_domicilio(self):
        orderitems = self.orderitem_set.all()
        negocios = []
        domicilio = 0
        if len(orderitems) >= 1:
            for item in orderitems:
                if not item.producto.negocio.pk in negocios:
                    negocios.append(item.producto.negocio.pk)
                    domicilio = domicilio + int(item.producto.negocio.costo) 
                else:
                    domicilio = 0
        return domicilio 


class OrderItem(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.producto.precio * self.quantity
        return total

    @property
    def get_domicilio(self):
        domicilio = int(self.producto.negocio.costo)
        return domicilio

    @property
    def get_negocio(self):
        negocio = self.producto.negocio.id
        return negocio


class ShippingOfertante(models.Model):
    ofertante = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    order_enviada = models.BooleanField(default=False)      
    fecha_envio = models.DateTimeField(verbose_name="Fecha de envio", blank=True, null = True)
    negocio = models.IntegerField(verbose_name='negocio', blank=True, null=True)


    class Meta:
        verbose_name = 'Shipping ofertante'           
        unique_together = (('ofertante', 'order'),)

Comercio/negocios/forms.py
from django import forms
from .models import Negocio, Producto, CategoriaNegocios


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('nombre', 'foto', 'precio')
        label = {
            'nombre': 'Nombre del Artículo',
            'foto': 'Foto del articulo',
            'precio': 'Precio del articulo',                        
        }
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre del Artículo'
                }
            ),
            'foto': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file mt-3'
                }
            ),
            'precio': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Precio del Artículo'
                }
            )            
        }

    


class NegocioForm(forms.ModelForm):

    class Meta:
        model = Negocio
        fields = ('nombre', 'fachada', 'direccion', 'telefono', 'email_negocio', 'domicilio', 'costo',
                  'categoria', 'descripcion', 'lon', 'lat')
        label = {
            'nombre': 'Nombre del Establecimiento',
            'fachada': 'Foto de la Fachada',
            'direccion': 'Dirección',
            'telefono': 'Telefono del Establecimiento',
            'domicilio': '¿Cuenta con servicio de domicilio?',
            'costo': 'Costo del Domicilio',
            'email_negocio': 'Email del Negocio',
            'categoria': 'Categoría del Establecimiento',
            'descripcion': 'Descripción',
            'lon': '',
            'lat': ''
        }

        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre del Negocio'
                }
            ),
            'fachada': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file mt-3'
                }
            ),
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Dirección del Establecimiento'
                }
            ),
            'telefono': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Telefono del Establecimiento'
                }
            ),
            'domicilio': forms.CheckboxInput(
                attrs={
                    'class': 'form-check'
                }
            ),
            'costo': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Costo del Domicilio',
                    'hidden': True
                }
            ),
            'email_negocio': forms.EmailInput(
                attrs={
                    'class': 'form-control form-control-user',
                    'placeholder': 'Correo Electrónico del Negocio'
                }
            ),
            'categoria': forms.Select(
                attrs={                
                    'class': 'form-control'                
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Descripción de su Establecimiento'
                }
            ),
            'lon': forms.NumberInput(
                attrs={
                    'hidden': True,
                    'required': True
                }
            ),
            'lat': forms.NumberInput(
                attrs={
                    'hidden': True,
                    'required': True
                }
            )
        }

Comercio/negocios/templates/negocios/correo_envio.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar reservacion</title>
</head>

<body>
    <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td class="active">{{item.producto.nombre}}</td>
                <td class="success">{{item.quantity}}</td>
                <td class="warning">${{item.get_total}}</td>
            </tr>
            {% endfor %}
            <tr>
                <td>Costo Domicilio</td>
                <td>${{domicilio}}</td>
            </tr>
            <tr>
                <td>Total (COP)</td>
                <td>${{total|floatformat:2}}</td>
            </tr>
        </tbody>
    </table>
    <div>
        Su pedido anteriormente descrito, fue enviado con exito el {{fecha}} por el negocio: {{negocio}}
    </div>

</body>

</html>

Comercio/negocios/templates/negocios/form_negocios.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Registrar negocio{% endblock %}

{% block control %}
{% include 'profiles/controlnav.html' %}
{% endblock %}

{% block content %}

{% if msj %}
<p>{{msj}}</p>
{% endif %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <!-- Approach -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Registrar negocio</h6>
        </div>
        <div class="card-body">
          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <div class="form-group ">
              <h5>Ubique la Dirección en el Mapa</h5>
              <div id='mapa' style='width: 100%; height: 300px;'></div>
            </div>
            
            <button class="btn btn-primary btn-block" type="submit">Registrar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block mapa %}
<script>




var long = {{user.perfil.lon|safe}}
var latt = {{user.perfil.lat|safe}}
long = long.toString()
latt = latt.toString()
long = parseFloat(long)


document.getElementById('id_lon').value = long;
document.getElementById('id_lat').value = latt;


  var mi_lon = long
  var mi_lat = latt
  
  mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcmVpOTRyZiIsImEiOiJja2Eyc3ZjZnkwMnJuM2xwb3dwMHV3aTJqIn0.ZXtAWhh4Ff7J0Qk0YEe5nw';
  var map = new mapboxgl.Map({
    container: 'mapa',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [mi_lon, mi_lat],
    zoom: 14,

  });

  var marker = new mapboxgl.Marker({
    draggable: true
  })
    .setLngLat([mi_lon, mi_lat])
    .addTo(map);

  function onDragEnd() {
    var lngLat = marker.getLngLat();

    document.getElementById('id_lon').value = lngLat.lng;
    document.getElementById('id_lat').value = lngLat.lat;
  }

  marker.on('dragend', onDragEnd);
</script>

<script>
  var long = {{user.perfil.lon|safe}}
  long = long.toString()
  long = parseFloat(long)
  console.log(long)
</script>
{% endblock %}


{% block js %}

<script type="text/javascript">

  $(function () {
    $("#id_domicilio").change(function () {
      if(!$(this).prop('checked')) {
        $('#id_costo').prop("hidden", true);
      } else {
        $('#id_costo').prop("hidden", false);
      }      
    });
  });
</script>

{% endblock %}

Comercio/negocios/templates/negocios/negocio_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Listado negocios{% endblock %}


{% block content %}
<main role="main">
  <div class="container">
    <div class="col-lg-12 mb-12">
      <div class="card shadow mb-6 text-center">
        <div class="card-header bg-secondary text-white">
          <strong>{{negocio.nombre}}</strong>
        </div>
        <div class="card-body">
          <div class="text-center">
            <img class="img-fluid px-3 px-sm-4 mt-3 mb-6" style="width: 10rem;" src="{{negocio.fachada.url}}" alt="">
          </div>
          <h4 class="card-subtitle mb-2 text-muted"><strong>{{negocio.direccion}}</strong></h4>

          <h4 class="small font-weight-bold">Popularidad<span class="float-right">{{porcentaje}}%</span>
          </h4>
          <div class="progress mb-4">
            <div class="{{color}}" role="progressbar" style="width: {{porcentaje}}%" aria-valuenow="100"
              aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <div class="form-group">
            <a href="{% url 'negocios:cali_list' pk=negocio.pk %}"
              class="btn btn-dark btn-block text-white">Comentarios</a>
          </div>
        </div>
      </div>
      <br>

      <div class="row">
        {% for producto in productos %}
        <div class="col-lg-4 mb-4">
          <div class="card shadow mb-4 text-center">
            <div class="card-header bg-info text-white">
              <strong>{{producto.nombre}}</strong>
            </div>
            <div class="card-body">
              <div class="text-center">
                <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{{producto.foto.url}}" alt="">
              </div>
              <h4 class="card-subtitle mb-2 text-muted">{{producto.precio}} <strong>COP</strong></h4>
              <a class="btn btn-dark btn-block text-white" onclick="mifuncion(numero={{producto.negocio.telefono}})"
                data-toggle="modal" data-target="#exampleModal" data-whatever="{{producto.negocio.id}}"><strong>Envianos
                  un mensaje</strong>
                <i class="fa fa-comment-dollar" style="font-size:36px"></i>
              </a>              
              <button data-product="{{producto.id}}" data-action="add" class="btn btn-dark btn-block text-white">Adiccionar al carrito</button>
            </div>
          </div><br>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</main>

<!--Modal ventana-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'negocios:calificacion_negocio' %}" method="GET">
          <div class="clasificacion">
            <center>
              <input id="radio1" type="radio" name="estrellas" value="100">
              <!--
              --><label for="radio1"><i class="fas fa-star fa-2x"></i></label>
              <!--
              --><input id="radio2" type="radio" name="estrellas" value="80">
              <!--
              --><label for="radio2"><i class="fas fa-star fa-2x"></i></label>
              <!--
              --><input id="radio3" type="radio" name="estrellas" value="60">
              <!--
              --><label for="radio3"><i class="fas fa-star fa-2x"></i></label>
              <!--
              --><input id="radio4" type="radio" name="estrellas" value="40">
              <!--
              --><label for="radio4"><i class="fas fa-star fa-2x"></i></label>
              <!--
              --><input id="radio5" type="radio" name="estrellas" value="20">
              <!--
              --><label for="radio5"><i class="fas fa-star fa-2x"></i></label>
              <input id="id_negocio" name="id_negocio" hidden>
            </center>
          </div>
          <div class="form-group">
            <label for="comentario" class="col-form-label">Comenta tu experiencia</label>
            <textarea class="form-control" name="comentario" id="comentario"></textarea>
          </div> 
          <button type="submit" class="btn btn-success btn-block"><span
              class="glyphicon glyphicon-off"></span>Califícanos</button>
          <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">No hice pedido</button>
        </form>
      </div>

    </div>
  </div>
</div>


{% endblock %}



{% block js-extra %}
<script>

  function mifuncion(numero){
    $('#exampleModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var recipient = button.data('whatever')
    var modal = $(this)
    modal.find('.modal-title').text('Califica nuestro servicio')
    modal.find('.modal-body input[name="id_negocio"]').val(recipient)
  }) 
  window.open('https://api.whatsapp.com/send?phone=57'+numero+'&text=Hola%21%2c%20cómo%20 estas%3f%20Te%20 encontré%20en%20sigelo.org%20y%20quiero%20pedirte%20un%20Domicilio&source=&data=&app_absent=', '_blank');

  }  
</script>

{% endblock %}

Comercio/negocios/templates/negocios/update_negocio.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}

<div class="container">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Modificar Negocios</h1>
  </div>
  <div class="form-group">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <div class="form-group">
        <h5> eUbique la Dirección en el Mapa</h5>
        <div id='mapa' style='width: 100%; height: 300px;'></div>
      </div>

      <button class="btn btn-success btn-block" type="submit">Actualizar</button>
    </form>
  </div>

</div>

{% endblock %}

{% block mapa %}
<script>


var long = {{user.perfil.lon|safe}}
var latt = {{user.perfil.lat|safe}}
long = long.toString()
latt = latt.toString()
long = parseFloat(long)


  var mi_lon = long
  var mi_lat = latt

  mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcmVpOTRyZiIsImEiOiJja2Eyc3ZjZnkwMnJuM2xwb3dwMHV3aTJqIn0.ZXtAWhh4Ff7J0Qk0YEe5nw';
  var map = new mapboxgl.Map({
    container: 'mapa',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [mi_lon, mi_lat],
    zoom: 14,

  });

  var marker = new mapboxgl.Marker({
    draggable: true
  })
    .setLngLat([mi_lon, mi_lat])
    .addTo(map);

  function onDragEnd() {
    var lngLat = marker.getLngLat();

    document.getElementById('id_lon').value = lngLat.lng;
    document.getElementById('id_lat').value = lngLat.lat;
  }

  marker.on('dragend', onDragEnd);
</script>
{% endblock %}


{% block js %}

<script type="text/javascript">

  $(function () {

    if($("#id_domicilio").prop('checked')){
      $('#id_costo').prop("hidden", false);
    };
    $("#id_domicilio").change(function () {
      if(!$(this).prop('checked')) {
        $('#id_costo').prop("hidden", true);
      } else {
        $('#id_costo').prop("hidden", false);
      }      
    });
  });
</script>

{% endblock %}