Comercio/Comercio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.urls import urlpatterns
from profiles.urls import registro_perfil
from negocios.urls import registro_negocios
from django.views.static import serve

# if settings.DEBUG:
#     path_server = 'ingi/obj3/'
# else:
#     path_server = ''
path_server = 'servicios/'
"""
urlpatterns = [
    path('', include(urlpatterns)),
    path(path_server + 'admin/', admin.site.urls),
    path(path_server + 'accounts/', include('allauth.urls')),
    path(path_server + 'me/', include(registro_perfil)),
    path(path_server + 'negocios/', include(registro_negocios)),
    path(path_server + '', include(urlpatterns)),
    path(path_server + 'servicios/', include('cal.urls')),
    #path('', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),
]
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('me/', include(registro_perfil)),
    path('negocios/', include(registro_negocios)),
    path('', include(urlpatterns)),
   # path('.well-known/pki-validation/6F4A35B1D5D68CDA4270F888D0D82FDC.txt', include(urlpatterns)),
    path('servicios/', include('cal.urls')),
    #path('servicios/', include(registro_negocios)),    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    from django.conf.urls.static import static
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Comercio/cal/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from . import views
from .views import CrearServicio, ServicioUpdate, ServicioDetail, calendar_view, service_schedule, ListReservation,ListMyReservation
from .views import ServicioList, CrearTiendaServicio, TiendaServicioList, TiendaServicioUpdate, DeleteTiendaServicio, CalificacionesTienda, DeleteComentarios


app_name = 'cal'
urlpatterns = [
    path('<str:pk>/calendar/', views.calendar_view, name='calendar'),
    path('<str:pk>/calendar/<str:flag>/', views.calendar_view, name='calendar'),
    path('<str:pk>/queues/<int:pk_service>/', views.queues, name='queues'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/reservaciones/<int:day>/',ListReservation.as_view(), name='listar_reservaciones'),
    path('<str:pk>/calendar/<str:flag>/<int:pk_service>/misreservaciones/<int:day>/',ListMyReservation.as_view(), name='listar_mis_reservaciones'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/', views.service_schedule, name='service_schedule'),
    path('<str:pk>/calendar/<int:pk_service>/<int:year>/<int:month>/<int:slug>/<int:user_r>/', views.service_schedule, name='service_schedule'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('', views.home, name='listar_servicio'),    
    path('<int:pk_tienda>/crear/', CrearServicio.as_view(), name='crear_servicio'),
    path('mis-servicio/<int:pk>', ServicioList.as_view(), name='mis-servicios'),
    path('delete/', views.DeleteServicio, name='delete_servicio'),
    path('editar/<int:pk>', ServicioUpdate.as_view(), name='editar_servicio'),
    path('detail/<int:pk>', ServicioDetail.as_view(), name='detail_servicio'),
    path('detalles/<int:pk>/', views.detallesServicio, name="detalles_Servicio"),
    ## urls de reservacion
    path('reservacion/confirmar/<int:pk>', views.ConfirmarReservacion , name='confirmar_reservacion'),
    path('reservacion/modal/estado', views.reservacion_modal, name='confirmarmodal'),
    path('crear/reservacion/for-client', views.AddReservationForClient, name='add-reservacion-client'),
    path('reservacion/llegada', views.ConfirmarLlegada, name='confirmacion-llegada'),
    # urls Tienda servicios
    path('tiendas/crear', CrearTiendaServicio.as_view(), name='crear-tienda'),
    path('me/tienda-servicios', TiendaServicioList.as_view(), name='tienda-list'),
    path('tienda/<int:pk>/', TiendaServicioUpdate.as_view(), name='tienda-update'),
    path('tienda/eliminar', DeleteTiendaServicio, name="tienda-delete"),    
    path('calificar-tienda/', views.calificacion_negocio, name='tienda-calificacion'),
    path('.well-known/pki-validation/B31859471C93FF9991984E7C0EF9F622.txt', views.ssl, name="ssl"),
    path('<int:pk_tienda>/comentarios/list/', CalificacionesTienda.as_view(), name="tienda-cali-list"),
    path('.well-known/pki-validation/284F712840C098E3B1903A9674547FA8.txt', views.ssl, name="ssl"),
    path('<str:pk>/service_agenda/<str:pk_service>/', views.service_agenda, name='service_agenda'),
    path('comentario/delete/', DeleteComentarios, name='delatecoment')
]

Comercio/core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from .views import HomePageView, HomePage1View
from django.urls import path


urlpatterns = ([
    #Aqui utilizamos nuestras CBV
    path('', HomePageView.as_view(), name="home"),
    path('prueba/mapa', HomePage1View.as_view())
], 'core')

Comercio/core/models.py
from django.db import models

# Create your models here.

Comercio/core/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages

from django.views.generic.base import TemplateView
from negocios.models import Negocio
from profiles.models import Perfil
from cal.models import Servicio, CategoriaServicio, TiendaServicio

import json


class LoginRequiredMixin(object):
    # esto es un mixxin
    """
    Este mixin requerira que el usuario sea miembro del satff
    """
    # coneste decorator nos aseguramos q no puedan crear contenido sino son staf
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)



@method_decorator(login_required, name='dispatch')
class HomePageView(TemplateView):
    template_name = "core/home.html"
    # Se redefine el metodo get para devolver el contexto que queramos
    # los *args, **kwars son por buena practica

    def get(self, request, *args, **kwargs):


        perfil = Perfil.objects.filter(id_user=request.user).exists()        
        # falso o true
        # si existe, es porque hay un perfil asociado
        # sino debe obligar a irse a crearlo
        if perfil == False:
            return redirect('profiles:crear_perfil')
        context = {}
        negocios = Negocio.objects.all()
        servicios = TiendaServicio.objects.all()
        print(servicios)
        negociosjson = construirjson(negocios)  # se invoca la funcion que retorna el json
        serviciosjson1 = serviciosjson(servicios)        
        negociosjson = json.dumps(negociosjson)
        serviciosjson1 = json.dumps(serviciosjson1)
        print(serviciosjson1)
        if len(negociosjson) <= 2:
            negociosjson = 1
        context['data'] = negociosjson
        context['servicios'] = serviciosjson1        
        return render(request, template_name=self.template_name, context=context)


def serviciosjson(query):
    """
    Esta funcion se encaga de retornar el json necesario para que las corrdenadas se muestren en
    el mapa central de la pagina
    """
    dic3 = {}
    lista = []
    for i in query:
        dic0 = {}
        dicq = {}
        dic2 = {}
        lista2 = []
        lista2.insert(0, i.lon)
        lista2.insert(1, i.lat)
        dicq['coordinates'] = lista2
        dic0['geometry'] = dicq
        dic2['title'] = i.nombre
        dic2['description'] = "<center><h6>" + i.direccion + "</h6></center>" + "<br><a class='btn btn-secondary btn-block' href='/servicios/detalles/"+str(i.pk)+"'>Ver Servicio</a> "+\
            '<br><a target="_blank" href="https://api.whatsapp.com/send?phone=57' + i.telefono + \
            '&text=Hola%21%2c%20cómo%20 estas%3f%20Te%20 encontré%20en%20sigelo.org%20y%20quiero%20pedirte%20un%20Servicio&source=&data=&app_absent=" class="btn btn-success btn-icon-split btn-sm">' +\
            '<span class="icon text-white-50">' +\
            '<i class="fab fa-whatsapp fa-2x"></i>' +\
            '</span>' +\
            '<span class="text small">Envíanos un mensaje por WhatsApp</span>' +\
            '</a>'
        dic0['properties'] = dic2
        lista.append(dic0)
        dic3['features'] = lista

    return dic3


def construirjson(query):
    """
    Esta funcion se encaga de retornar el json necesario para que las corrdenadas se muestren en
    el mapa central de la pagina
    """
    dic3 = {}
    lista = []

    for i in query:
        dic0 = {}
        dicq = {}
        dic2 = {}

        lista2 = []
        lista2.insert(0, i.lon)
        lista2.insert(1, i.lat)
        dicq['coordinates'] = lista2
        dic0['geometry'] = dicq
        if i.costo == '0':
            costo = 'Gratis'
        else:
            costo = i.costo

        dic2['title'] = i.nombre
        dic2['description'] = '<div class="h5 mb-2 font-weight-bold text-gray-800">' + i.direccion + '</div>' +\
                "<center>Domicilio<h6>" + costo + "</h6></center>" +\
                    '<a href="negocios/' + str(i.id) + \
            '/store_detail/" class="btn btn-secondary btn-icon-split btn-sm">' +\
            '<span class="icon text-white-50">' +\
            '<i class="fa fa-home fa-2x"></i>' +\
            '</span>' +\
            '<span class="text small">Visita nuestra tienda y conoce nuestros productos</span>' +\
            '</a>' +\
            '<p></p><a target="_blank" href="https://api.whatsapp.com/send?phone=57' + i.telefono + \
            '&text=Hola%21%2c%20cómo%20 estas%3f%20Te%20 encontré%20en%20sigelo.org%20y%20quiero%20pedirte%20un%20Domicilio&source=&data=&app_absent=" class="btn btn-success btn-icon-split btn-sm">' +\
            '<span class="icon text-white-50">' +\
            '<i class="fab fa-whatsapp fa-2x"></i>' +\
            '</span>' +\
            '<span class="text small">Envíanos un mensaje por WhatsApp</span>' +\
            '</a>' +\
            '</div>'
        dic0['properties'] = dic2
        lista.append(dic0)
        dic3['features'] = lista

    return dic3


class HomePage1View(TemplateView):
    template_name = "core/map.html"
    # Se redefine el metodo get para devolver el contexto que queramos
    # los *args, **kwars son por buena practica

Comercio/core/templates/core/botones.html
{% extends 'core/base.html' %}
{% block content %}


<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Buttons</h1>

    <div class="row">

        <div class="col-lg-6">

            <!-- Circle Buttons -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Circle Buttons</h6>
                </div>
                <div class="card-body">
                    <p>Use Font Awesome Icons (included with this theme package) along with the circle buttons as shown
                        in the examples below!</p>
                    <!-- Circle Buttons (Default) -->
                    <div class="mb-2">
                        <code>.btn-circle</code>
                    </div>
                    <a href="#" class="btn btn-primary btn-circle">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="#" class="btn btn-success btn-circle">
                        <i class="fas fa-check"></i>
                    </a>
                    <a href="#" class="btn btn-info btn-circle">
                        <i class="fas fa-info-circle"></i>
                    </a>
                    <a href="#" class="btn btn-warning btn-circle">
                        <i class="fas fa-exclamation-triangle"></i>
                    </a>
                    <a href="#" class="btn btn-danger btn-circle">
                        <i class="fas fa-trash"></i>
                    </a>
                    <!-- Circle Buttons (Small) -->
                    <div class="mt-4 mb-2">
                        <code>.btn-circle .btn-sm</code>
                    </div>
                    <a href="#" class="btn btn-primary btn-circle btn-sm">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="#" class="btn btn-success btn-circle btn-sm">
                        <i class="fas fa-check"></i>
                    </a>
                    <a href="#" class="btn btn-info btn-circle btn-sm">
                        <i class="fas fa-info-circle"></i>
                    </a>
                    <a href="#" class="btn btn-warning btn-circle btn-sm">
                        <i class="fas fa-exclamation-triangle"></i>
                    </a>
                    <a href="#" class="btn btn-danger btn-circle btn-sm">
                        <i class="fas fa-trash"></i>
                    </a>
                    <!-- Circle Buttons (Large) -->
                    <div class="mt-4 mb-2">
                        <code>.btn-circle .btn-lg</code>
                    </div>
                    <a href="#" class="btn btn-primary btn-circle btn-lg">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="#" class="btn btn-success btn-circle btn-lg">
                        <i class="fas fa-check"></i>
                    </a>
                    <a href="#" class="btn btn-info btn-circle btn-lg">
                        <i class="fas fa-info-circle"></i>
                    </a>
                    <a href="#" class="btn btn-warning btn-circle btn-lg">
                        <i class="fas fa-exclamation-triangle"></i>
                    </a>
                    <a href="#" class="btn btn-danger btn-circle btn-lg">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>

            <!-- Brand Buttons -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Brand Buttons</h6>
                </div>
                <div class="card-body">
                    <p>Google and Facebook buttons are available featuring each company's respective brand color. They
                        are used on the user login and registration pages.</p>
                    <p>You can create more custom buttons by adding a new color variable in the
                        <code>_variables.scss</code> file and then using the Bootstrap button variant mixin to create a
                        new style, as demonstrated in the <code>_buttons.scss</code> file.</p>
                    <a href="#" class="btn btn-google btn-block"><i class="fab fa-google fa-fw"></i> .btn-google</a>
                    <a href="#" class="btn btn-facebook btn-block"><i class="fab fa-facebook-f fa-fw"></i>
                        .btn-facebook</a>

                </div>
            </div>

        </div>

        <div class="col-lg-6">

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Split Buttons with Icon</h6>
                </div>
                <div class="card-body">
                    <p>Works with any button colors, just use the <code>.btn-icon-split</code> class and the markup in
                        the examples below. The examples below also use the <code>.text-white-50</code> helper class on
                        the icons for additional styling, but it is not required.</p>
                    <a href="#" class="btn btn-primary btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-flag"></i>
                        </span>
                        <span class="text">Split Button Primary</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-success btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-check"></i>
                        </span>
                        <span class="text">Split Button Success</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-info btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-info-circle"></i>
                        </span>
                        <span class="text">Split Button Info</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-warning btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-exclamation-triangle"></i>
                        </span>
                        <span class="text">Split Button Warning</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-danger btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-trash"></i>
                        </span>
                        <span class="text">Split Button Danger</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-secondary btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">Split Button Secondary</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-light btn-icon-split">
                        <span class="icon text-gray-600">
                            <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">Split Button Light</span>
                    </a>
                    <div class="mb-4"></div>
                    <p>Also works with small and large button classes!</p>
                    <a href="#" class="btn btn-primary btn-icon-split btn-sm">
                        <span class="icon text-white-50">
                            <i class="fas fa-flag"></i>
                        </span>
                        <span class="text">Split Button Small</span>
                    </a>
                    <div class="my-2"></div>
                    <a href="#" class="btn btn-primary btn-icon-split btn-lg">
                        <span class="icon text-white-50">
                            <i class="fas fa-flag"></i>
                        </span>
                        <span class="text">Split Button Large</span>
                    </a>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

Comercio/core/templates/core/contenido.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Cards</h1>
    </div>

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Milton (Monthly)
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Earnings (Annual)
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar" style="width: 50%"
                                            aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Pending Requests
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-6">

            <!-- Default Card Example -->
            <div class="card mb-4">
                <div class="card-header">
                    Default Card Example
                </div>
                <div class="card-body">
                    This card uses Bootstrap's default styling with no utility classes added. Global
                    styles are the only
                    things modifying the look and feel of this default card example.
                </div>
            </div>

            <!-- Basic Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Basic Card Example</h6>
                </div>
                <div class="card-body">
                    The styling for this basic card example is created by using default Bootstrap
                    utility classes. By
                    using utility classes, the style of the card component can be easily modified with
                    no need for any
                    custom CSS!
                </div>
            </div>

        </div>

        <div class="col-lg-6">

            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Dropdown Card Example</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    Dropdown menus can be placed in the card header in order to extend the functionality
                    of a basic
                    card.
                    In this dropdown card example, the Font Awesome vertical ellipsis icon in the card
                    header can be
                    clicked on in order to toggle a dropdown menu.
                </div>
            </div>

            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button"
                    aria-expanded="true" aria-controls="collapseCardExample">
                    <h6 class="m-0 font-weight-bold text-primary">Collapsable Card Example</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample">
                    <div class="card-body">
                        This is a collapsable card example using Bootstrap's built in collapse
                        functionality.
                        <strong>Click
                            on the card header</strong> to see the card body collapse and expand!
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

Comercio/core/templates/core/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; SIGELO 2020</span>
        </div>
    </div>
</footer>

Comercio/core/templates/core/hola.html
 <!-- Aquí va el controlnav -->
 <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->

    {% if user.is_authenticated %}
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:home' %}">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">Bienvenido: {{ user.username }}<sup> </sup>
      </div>
    </a>
    {% if user.perfil.ingresos %}
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'core:home' %}">
        <i class="fa fa-shopping-bag"></i>
        <span>Inicio</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'profiles:Perfillist' %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Mi panel de control</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'negocios:list_negocios' %}">
        <i class="fa fa-map-marker"></i>
        <span>Tus negocios aquí!</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'cal:tienda-list' %}">
        <i class="fa fa-bullhorn"></i>
        <span>Tus servicios aquí!</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="#">
        <i class="fa fa-shopping-bag"></i>
        <span>Encuesta donaciones</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" data-toggle="modal" data-target="#logoutModal">
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Salir
      </a>
    </li>
    <hr class="sidebar-divider my-0">
    {% endif %}
    {% if not user.perfil.ingresos %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'core:home' %}">
        <i class="fa fa-shopping-bag"></i>
        <span>Inicio</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'profiles:Perfillist' %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Mi panel de control</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="#">
        <i class="fa fa-shopping-bag"></i>
        <span>Encuesta donaciones</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" data-toggle="modal" data-target="#logoutModal">
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Salir
      </a>
    </li>
    <hr class="sidebar-divider my-0">
    {% endif %}
    {% else %}
    <!-- Nav Item - Dashboard -->
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'account_login' %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Debes iniciar sesion</span></a>
    </li>
    {% endif %}